networks:
  default:
    name: xoxxox_netmid
    external: true
services:
  xoxxox_tttsim:
    image: xoxxox/envweb:001
    container_name: xoxxox_ttttry
    volumes:
    - ../../../export:/opt/common
    env_file:
    - ./envdir.txt
    ports:
    - 10302:80
    command: "python /opt/common/bin/xoxxox/srvttt_opt.py --engine xoxxox/engine_ttttry"
